### PR TITLE
big rewrite!

### PR DESCRIPTION
**Pull request by radio-alice**
Hi I've been working on this one for a bit. It's pretty big, so no rush on looking it over.

Basically re-architected it from scratch while keeping almost all of the business logic the same. Added a reference.md file that lists all the changes and tries to explain how its architected + how one would work in this architecture.

As I said earlier, I know this is some pretty big changes so no worries if you don't want to merge. But you should def look through the code– I feel really good about how clean and modular it is!

I can get started on fixing merge conflicts, if you're interested in getting this in at some point.

P.S. sorry for doing it all in one commit, but the changes didn't really make sense unless they were all together.

### CODE REVIEW

**Comment by radio-alice** [comment]
for some reason no matter what editor I open it in, the only merge conflicts it will let me edit are in .gitignore– everything else gets squashed by the master branch. can't figure out why :/

actually the github builtin editor works, but it makes you resolve everything by hand and that seems like a recipe for disaster here

any ideas?

**Comment by alexwennerberg** [comment]
Quoting Zach Sherman (2020-08-23 10:31:57)
> for some reason no matter what editor I open it in, the only merge conflicts it will let me edit are in .gitignore– everything else gets squashed by the master branch. can't figure out why :/
> 
> actually the github builtin editor works, but it makes you resolve everything by hand and that seems like a recipe for disaster here
> 
> any ideas?

I'll give it a shot -- there aren't too many changes I need to make I
think

**Comment by radio-alice** [comment]
Oops I just did it on GitHub by hand

**Comment by alexwennerberg** [comment]
Quoting Zach Sherman (2020-08-23 11:08:54)
> Oops I just did it on GitHub by hand

Oh nice -- let me know when you've finished

**Comment by radio-alice** [comment]
Ok this branch should be in the correct final state now– not sure where git is finding merge conflicts, but those should be safe to just override with the current branch

**Comment by radio-alice** [comment]
we good! 🥵

**Comment by alexwennerberg** [comment]
OK I'm going to merge and do some more testing/cleanup on master before I deploy. Thanks a ton!

**Pull request merged**
